# This rule is not used by the project aks-health-guard-clean itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to monitoring.healthcheck.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aks-health-guard-clean
    app.kubernetes.io/managed-by: kustomize
  name: workload-viewer-role
rules:
- apiGroups:
  - monitoring.healthcheck.dev
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.healthcheck.dev
  resources:
  - workloads/status
  verbs:
  - get
