apiVersion: monitoring.healthcheck.dev/v1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: aks-health-guard-clean
    app.kubernetes.io/managed-by: kustomize
  name: workload-sample
spec:
  jobName: "my-fake-job"
  thresholds:
    cpuUsageNano: 200000000 # 200m
    memoryUsageBytes: 209715200 # 200Mi
    maxRestartCount: 10
    maxPendingTime: "60s"
status:
  health: true
  evaluated: false
